---
#
# HTTPD customization tasks
#

- name: Update webserver port
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: "Listen 80"
    replace: "Listen {{ ports.http }}"
    backup: yes
  notify:
    - restart_webserver 
