---
# tasks file for apache_test

- name: Install Apache httpd
  yum:
    name: "{{ packages }}"
    state: latest
  tags:
    - setup_httpd

- name: Start and Enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ services }}"
  tags:
    - setup_httpd

- name: Include httpd customization tasks
  include_tasks: custom_httpd.yml
  tags:
    - setup_httpd

- name: Allow http port
  firewalld:
    port: "{{ports.http}}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  tags:
    - setup_httpd

- name: Include web content tasks
  include_tasks: add_htmls.yml
  tags:
    - setup_httpd

- name: Include Test HTTPD tasks
  include_tasks: test_httpd.yml
  tags:
    - test_httpd

